name: build
on: [push, pull_request]
jobs:
  build-by-stack:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        resolver:
          - lts-3
          - lts-6
          - lts-7
          - lts-9
          - lts-11
          - lts-12
          - lts-13
          - lts-14
          - lts-15
          - lts-16
          - lts-17
          - lts-18
    name: Stack by resolver is ${{ matrix.resolver }}
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-version: "latest"
      - run: stack test --resolver ${{ matrix.resolver }}
  build-by-cabal:
    runs-on: ubuntu-18.04 # 古いUbuntuのバージョンでないと、古いGHCが動かないようです。
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - 7.4.1
          - 7.4.2
          - 7.6.3
          - 7.8.4
          - 7.10.3
          - 8.0.2
          - 8.2.2
          - 8.4.1
          - 8.4.2
          - 8.4.3
          - 8.4.4
          - 8.6.1
          - 8.6.2
          - 8.6.3
          - 8.6.4
          - 8.6.5
          - 8.8.1
          - 8.8.2
          - 8.8.3
          - 8.8.4
          - 8.10.1
          - 8.10.2
          - 8.10.3
          - 8.10.4
          - 9.0.1
    name: Cabal by GHC version is ${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y libnuma-dev
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: cabal test
